### ISSUE TITLE
Wrong candidate ages

### ISSUE THREAD

**Issue by Wyclef** [MyanmarAPI/dataset#1]
Candidates with the following IDs seem to have wrong ages:
`5a4af2c93f78c7e73183534cd51864f3`
`9f6b62139562e3b94d828dc903c664b5`

**Comment by mapmeld** [comment]
Thanks! birthday issues will be resolved in the next update

**Comment by yehtoo** [comment]
Yeah . . actually it was 'birthdate' attribute from Candidate Endpoint. We used to calculate candidate's age from 'birthdate' assuming as it's Unix Timestamp. But it goes something wrong in these two candidates. Thanks.

**Comment by mapmeld** [comment]
it should be good now!

**Comment by yehtoo** [comment]
Thanks Nick. 
:+1:

**Comment by Wyclef** [comment]
Thanks!
