### ISSUE TITLE
Candidate's photo cannot be fetched

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/dataset#10]
There is photo url for the candidate `0e818a2afd5f22a954a3b8f6f85f554a` but It shows an error loading the url.

**Comment by nyanlynnhtut** [comment]
Ping @tyohan

**Comment by tyohan** [comment]
@phyominthu @nyanlynnhtut the file actually not exist in our google storage. So @mapmeld can you send me the original file so I can crop it and upload it to our google storage.

**Comment by mapmeld** [comment]
@tyohan use this one 
![screen shot 2015-10-08 at 7 41 51 am](https://cloud.githubusercontent.com/assets/643918/10365261/1b4080c6-6d90-11e5-8ea7-1d72ef1ac134.png)

**Comment by tyohan** [comment]
Uploaded.
