### ISSUE TITLE
Wrong data on candidate

### ISSUE THREAD

**Issue by tyohan** [MyanmarAPI/dataset#11]
Check candidate 2446aa365773daeb4d0af282ace26eff.  It has a female photo while the candidate is a male candidate. His name in Myanmar also appears with weird character at the end.

Candidate ID: 2446aa365773daeb4d0af282ace26eff

Candidate Name: ဦးသန်းဋ္ဌေး

Photo ID: 5924

House: အမျိုးသားလွှတ်တော်

State: ရှမ်း

Constituency No: 3

Party: အမျိုးသားဒီမိုကရေစီအဖွဲ့ချုပ်ပါတီ

**Comment by mapmeld** [comment]
fixed in next update
