### ISSUE TITLE
No Abbreviation for Party

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/dataset#13]
Hi,

Once, there was `abbreviation` available as `NLD` for party id `40`. But now it's empty string. It's a popular party and I'm worried users have problems searching it by abbreviation.

Thanks.

**Comment by mapmeld** [comment]
The abbreviation NLD isn't on the official UEC page: http://uecmyanmar.org/index.php/voters/86-2013-05-08-09-12-08/199-2013-11-14-07-50-37
