### ISSUE TITLE
Candidate photo cannot be fetched

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/dataset#17]
Hi,

Candidate `115a188a01909c46785c71ff09ee9c15` has `photoUrl` but photo cannot be fetched. The link returns an error.

Ping @tyohan

**Comment by mapmeld** [comment]
@tyohan please use this picture

![screen shot 2015-10-18 at 9 24 14 pm](https://cloud.githubusercontent.com/assets/643918/10569668/a093c4ee-75de-11e5-9e71-da1bfeb7a03e.png)

**Comment by tyohan** [comment]
@phyominthu image uploaded.
