### ISSUE TITLE
Two state/region constituencies having same wards

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/dataset#20]
In **states_regions.csv**,

State/Region: `ပဲခူးတိုင်းဒေသကြီး`
Constituency Name: `လက်ပံတန်းမြို့နယ်`
Constituency Number: `1` and `2` have same wards and village tracts.

**Comment by mapmeld** [comment]
@phyominthu sorry it looks like I copied the same list twice! The true list is in the PDF in parliament-parser: https://github.com/MyanmarAPI/parliament-parser/tree/master/pdf  and we're working to get it typed up

**Comment by mapmeld** [comment]
@phyominthu thanks! just pushed the fixed list to this repo
