### ISSUE TITLE
Wrong cropped photo - candidate_id a5d8e217bc2630a7ce7efa801b20c8c4

### ISSUE THREAD

**Issue by DragonVirus** [MyanmarAPI/dataset#21]
candidate_id - a5d8e217bc2630a7ce7efa801b20c8c4
candidate name - ဦးစိုင်းထွန်းအောင်
photo_url - https://storage.googleapis.com/staticassets/candidate-photos/Scan_E_20150825_050.jpg

**Comment by mapmeld** [comment]
@tyohan this is one of the photos in the ZIP I sent you by e-mail
