### ISSUE TITLE
Please add winning results for 2017 candidates

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/dataset#25]
So, the by-election results are confirmed. Referencing to official announcements by UEC, I've made a Google sheet for all 19 results [here](https://docs.google.com/spreadsheets/d/1CCiHendZSx0uuxjFT4kOeVUwrD5hzhIEnwzpouOz4k4/edit?usp=sharing).

Can you please add this data to the candidates? If you have any concern or need any help with the data, please let me know.

**Comment by DragonVirus** [comment]
@phyominthu vote count for ဒေါ်နန်းကောင်ခမ်း from State/Region , Shan constituency no.2 is missing.

**Comment by phyominthu** [comment]
@DragonVirus Yes, her vote count is missing because that number was blurry in UEC's online announcement. But she's the winner for sure.

And thanks for the update! 🍻
