### ISSUE TITLE
There are seven parties which have no candidates in any house in candidate endpoint

### ISSUE THREAD

**Issue by tyohan** [MyanmarAPI/dataset#3]
Below are the 7 parties those have this issue
- ၈၈မျိုးဆက်ကျောင်းသားလူငယ်များ(ပြည်ထောင်စုမြန်မာနိုင်ငံ)ပါတီ
- ပြည်ထောင်စုမြန်မာနိုင်ငံအမျိုးသားနိုင်ငံရေးအဖွဲ့ချုပ်ပါတီ 
- စည်းလုံးညီညွတ်ရေးနှနှင့်ဒီမိုကရေစီပါတီ ကချင်ပြည်နယ်(စဒက)
- ကရင်ပြည်နယ်ဒီမိုကရေစီနှင့်ဖွံ့ဖြိုးတိုးတက်ရေးပါတီ
- အမျိုးသားဖွံ့ဖြိုးတိုးတက်ရေးနှင့်ငြိမ်းချမ်းရေးပါတီ
- မြန်မာ့အမျိုးသားကွန်ဂရက်ပါတီ
- မြန်မာနိုင်ငံ တောင်သူ လယ်သမား အလုပ်သမား ပြည်သူ့ပါတီ

**Comment by mapmeld** [comment]
ok, we believe အမျိုးသားဖွံ့ဖြိုးတိုးတက်ရေးနှင့်ငြိမ်းချမ်းရေးပါတီ does not have any candidates on the ballot

the other parties will be included in the next data update. De-duping a couple of people and then we'll be ready

**Comment by tyohan** [comment]
@mapmeld is the data update solve this issue already?
