### ISSUE TITLE
Missing information in some parties

### ISSUE THREAD

**Issue by Wyclef** [MyanmarAPI/dataset#4]
1. Party ID `16`'s `party_seal` is `0`.
2. Party ID `66`'s `party_name_english` is `0`.
3. Party ID `77`'s `party_name_english` is blank (not sure if they have an English name though).

**Comment by mapmeld** [comment]
16: @tyohan @DragonVirus https://storage.googleapis.com/staticassets/flags-and-logos/16-flag.png and https://storage.googleapis.com/staticassets/flags-and-logos/16-logo.png are both in the data CSV

66 and 77: No English names: http://uecmyanmar.org/index.php/voters/86-2013-05-08-09-12-08/334-2014-07-21-04-50-11 and http://uecmyanmar.org/index.php/voters/86-2013-05-08-09-12-08/552-10-6-2015-ino-2

**Comment by tyohan** [comment]
@DragonVirus can you update the party data. In our CSV we have the data cc @mapmeld

**Comment by DragonVirus** [comment]
@Wyclef And party_id `16` have `party_seal`. It's not "0" when i called the current api. 
@tyohan i don't see above fixes in current party csv file. Just some spelling fixes in there.

**Comment by DragonVirus** [comment]
@mapmeld okay i changed the party_id `66` value to blank instead of "0" before importing. If you are okay, i will also push it to dataset. Since there's no english name for party 66 and 77. We are good here.
