### ISSUE TITLE
Party ID 38 could be wrong

### ISSUE THREAD

**Issue by tyohan** [MyanmarAPI/dataset#5]
Is there any issue with this party flag
<img width="643" alt="screen shot 2015-09-30 at 12 02 17 pm" src="https://cloud.githubusercontent.com/assets/106703/10184154/2fc8d6ae-676b-11e5-954a-7df8b409b20b.png">

**Comment by mapmeld** [comment]
Looks legit:
38: http://uecmyanmar.org/index.php/voters/86-2013-05-08-09-12-08/197-2013-11-14-07-32-32

41: http://uecmyanmar.org/index.php/voters/86-2013-05-08-09-12-08/200-2013-11-14-08-01-53
