### ISSUE TITLE
Upper House Constituency Pcode mistake for districts in Nay Pyi Taw

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/dataset#6]
Upper House candidates in two Nay Pyi Taw districts (constituencies) has a `constituency_name` as `မန္တလေး` (Mandalay). But the `constituency_st_pcode` is **MMR018** (which is the Nay Pyi Taw Union Territory's PCode).

Their `constituency_number`s are 9 and 10. So I guess they're actually from **MMR010** (Mandalay).

**Comment by mapmeld** [comment]
we're looking into this now, but it looks like this is how Naypyitaw is represented in the upper house and official MIMU data
