### ISSUE TITLE
There are still two parties which have no candidates in any house in candidate endpoint

### ISSUE THREAD

**Issue by yewintaung** [MyanmarAPI/dataset#7]
Below are 2 parties that have no candidates until candidate endpoint version 12
- ကရင်ပြည်နယ်ဒီမိုကရေစီနှနှင့်ဖွံ့ဖြိုးတိုးတက်ရေးပါတီ Kayin State Democracy and Development  Party
- အမျိုးသားဖွံ့ဖြိုးတိုးတက်ရေးနှင့်ငြိမ်းချမ်းရေးပါတီ National Development and Peace Party

**Comment by mapmeld** [comment]
- I forgot to fix spelling on ကရင်ပြည်နယ်ဒီမိုကရေစီနှင့်ဖွံ့ဖြိုးတိုးတက်ရေးပါတီ - it will have 9 candidates in the next update
- We believe that အမျိုးသားဖွံ့ဖြိုးတိုးတက်ရေးနှင့်ငြိမ်းချမ်းရေးပါတီ does not have any candidates on the ballot

**Comment by tyohan** [comment]
@mapmeld can we close this now Nic?
