### ISSUE TITLE
Duplicate candidate 

### ISSUE THREAD

**Issue by DragonVirus** [MyanmarAPI/dataset#8]
@yanoak inform me about that this morning. 
@mapmeld Please check this two candidates. They seem like a same person except it's not on the same house. Can a person run on 2 houses ? 
4f649b5901cc28d0cd4a1c6ecf06948e
2b2ec4fd113b2a1238f9fd22edaa931a
cc @tyohan

**Comment by mapmeld** [comment]
When people have the same or very close name, there are a few cases like this where we assigned them twice... It looks like we missed this one. I'll keep one and use the right details for the other

**Comment by mapmeld** [comment]
The state/regions candidate is fixed in the next update
