### ISSUE TITLE
Wrong photo and info for candidate

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/dataset#9]
Candidate ID = cca4fc27b25f6a678262ff2ca281004e has wrong photo and info.

**Comment by DragonVirus** [comment]
@mapmeld that one `cca4fc27b25f6a678262ff2ca281004e` and `54fe3116150289a7a2b3cf094a319918` have same info. Name is ဦးသောင်းထိုက် One is at lower house and the other at state/region

**Comment by mapmeld** [comment]
now fixed
